#!/usr/bin/env bash

# a hack install script for bunsen-netinstall
# part of 'bunsen-wayland'
# (c) Copyright: 2024 Mick Amadio <01micko@gmail.com>
# gplv3 licence
# conflicts with lxappearance, bl-exit

# DOTdesktops
echo "copying application .desktop files."
sudo cp -a applications/* /usr/share/applications/ || exit 1

# scripts
echo "copying scripts."
sudo chown root:root bin/* || exit 1
sudo cp -a bin/* /usr/bin/ || exit 1

# configs
echo "copying configs."
sudo chown root:root skel/.config/* || exit 1
sudo cp -arf skel/.config/* /usr/share/bunsen/skel/.config/ || exit 1

# session
echo "copying sessions."
sudo chown root:root wayland-sessions/* || exit 1
sudo cp -a wayland-sessions/* /usr/share/wayland-sessions/ || exit 1

# man page
echo "copying man pages."
sudo chown root:root man/* || exit 1
sudo cp -a man/man1/* /usr/share/man/man1/ || exit 1

# man page
echo "copying default autostart."
sudo cp -a lib/* /usr/lib/bunsen/configs/bunsen-autostart || exit 1

echo "Done!" && exit 0



