#!/usr/bin/env bash

# a hack install script for bunsen-netinstall
# part of 'bunsen-wayland'
# (c) Copyright: 2024 Mick Amadio <01micko@gmail.com>
# gplv3 licence
# conflicts with lxappearance, bl-exit

# DOTdesktops
echo "copying application .desktop files."
sudo cp -a applications/* /usr/share/applications/ || exit 1

# scripts
echo "copying scripts."
sudo chown root:root bin/* || exit 1
sudo cp -a bin/* /usr/bin/ || exit 1

# configs
echo "copying configs."
sudo chown root:root skel/.config/* || exit 1
sudo cp -arf skel/.config/* /usr/share/bunsen/skel/.config/ || exit 1

# session
echo "copying sessions."
sudo chown root:root wayland-sessions/* || exit 1
sudo cp -a wayland-sessions/* /usr/share/wayland-sessions/ || exit 1
if [ ! -x /usr/bin/openbox ] ; then
    echo "removing xsession"
    sudo rm -f /usr/share/xsessions/bunsenlabs.desktop || exit 1
fi

# netsurf fixup hack
echo "netsurf icon fixup hack"
[ -f /usr/share/applications/netsurf-gtk.desktop ] && \
    sudo sed -i 's/netsurf\.png/netsurf/' \
    /usr/share/applications/netsurf-gtk.desktop || exit 1

# themes fixup hack, from defaults in skell
echo "setting themes to bunsen defaults"
themefile=/usr/share/bunsen/skel/.config/gtk-3.0/settings.ini
[ -z "$themefile" ] && exit 1
gtktheme="$(grep 'gtk-theme-name' $themefile)"
g="${gtktheme/gtk-theme-name=/}"
icotheme="$(grep 'icon-theme-name' $themefile)"
i="${icotheme/gtk-icon-theme-name=/}"
curtheme"=$(grep 'cursor-theme-name' $themefile)"
c="${curtheme/gtk-cursor-theme-name=/}"
echo "gtk: $g ; ico: $i ; cur: $c"
#gsettings get org.gnome.desktop.interface cursor-theme
n=0
for t in gtk-theme icon-theme cursor-theme
     case $n in
         0)theme="$g"
         1)theme="$i"
         2)theme="$c"
     esac
     echo setting "$t : $theme"
     gsettings set org.gnome.desktop.interface $t "$theme" || exit 1
     n=$((n + 1))
done
  
echo "Done!" && sleep 2 && exit 0


